services:
  - type: web
    name: ai-voice-bot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn main:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: PORT
        value: 8000 